name : saluuuut
on: [push]
jobs:
    job2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - run: echo ${{ github.ref }}
            - run:  du -skh --exclude=".git"